use lib qw(/home/laoye/sites/advertise/lib);
use Apache2::RequestRec();
use Apache2::RequestIO();
use APR::Table();
use Apache2::ServerRec ();
use Apache2::ServerUtil ();
use Apache2::Connection ();
use Apache2::Log ();
use ModPerl::Registry ();
use Apache2::RequestUtil();
use Apache2::Const -compile => qw(OK DECLINED REDIRECT);
use Apache::DBI ();
use DBI ();
use Class::Handle;
use Class::SQL;
use Class::Toolkit;
use Class::User;
use Class::Utility;
use Class::Session;
use Class::Language;
use Class::Initialize;
use Class::Email;
use Class::Cookie;
use Class::Content;
use Class::BaseObject;
use Class::Advertise;
use Class::Time;
Apache::DBI->connect_on_init("dbi:mysql:advertise","aduser","adpassword");
1;
